#!/bin/bash
# Stop and remove all containers
docker stop $(docker ps -aq) 2>/dev/null
docker rm $(docker ps -aq) 2>/dev/null
# Remove all images
docker rmi $(docker images -q) 2>/dev/null
# Remove all volumes
docker volume rm $(docker volume ls -q) 2>/dev/null
# Optionally, prune dangling images
docker image prune -f
echo "All Docker containers, images, and volumes have been removed."
